# Generated by Django 3.2.22 on 2023-10-15 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_favoritelist'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='favoritelist',
            table='profiles_favoritelist',
        ),
    ]
