# Generated by Django 3.2.22 on 2023-10-15 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_favoritelist_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='favoritelist',
            table=None,
        ),
    ]
