# Generated by Django 3.2.22 on 2023-10-14 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_flowers_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowers',
            name='favorites',
        ),
    ]
